default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ecommerce
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: easytrade_developement
  port: 5432
  username: ecommerce
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  adapter: postgresql
  database: easytrade_test
  encoding: unicode
  username: ecommerce
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  adapter: postgresql
  database: easytrade_developement
  username: ecommerce
  password: <%= ENV['DB_PASSWORD'] %>
