default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 123456

development:
  <<: *default
  database: easytrade_developement
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: easytrade_test
  encoding: unicode

production:
  <<: *default
  adapter: postgresql
  database: easytrade_production
